//! GFEF Control Plane Module
//!
//! Triple IP Lock™ Architecture for NULL SPACE AI Inference Network
//!
//! GFEF (Galois Field Eigenmode Folding) enables:
//! - 19.6× weight reduction through spectral sparsity
//! - Combined with UAO-QTCAM: 24,500× total compression
//!
//! This module provides:
//! - GFEF Index extraction from customer model weights (via gfef-extract CLI)
//! - GFEF Index generation from weight data
//! - Real-time activation prediction API
//! - Calibration matrix rotation (60-second cycle)
//! - Subscription management for tiered access
//!
//! ## Triple IP Lock™ Architecture
//!
//! **Lock 1: GFEF Index** (this module)
//! - Spectral signatures extracted from customer weights
//! - NEVER leaves the Control Plane
//! - Generated by gfef-extract CLI when models uploaded via VXLAN
//!
//! **Lock 2: Calibration Matrix** (calibration.rs)
//! - Rotates every 60 seconds
//! - Input transformation for activation prediction
//!
//! **Lock 3: Activation Prediction API** (prediction.rs)
//! - Real-time oracle service
//! - Returns which neurons will activate (top-k%)

pub mod api;
pub mod calibration;
pub mod extraction;
pub mod index;
pub mod prediction;
pub mod storage;
pub mod subscription;
pub mod watcher;
pub mod websocket;

// Re-export main types
pub use api::{create_router as create_gfef_router, AppState as GFEFAppState};
pub use calibration::{CalibrationService, CalibrationMatrix};
pub use extraction::{ExtractionService, ExtractionConfig, ExtractionResult, ExtractionStats};
pub use index::{GFEFIndexGenerator, IndexConfig, IndexMetadata};
pub use prediction::{ActivationPredictor, PredictionRequest, PredictionResponse};
pub use storage::IndexStorage;
pub use subscription::{SubscriptionManager, SubscriptionTier, Subscription};
pub use watcher::{ModelWatcherService, WatcherConfig, WatcherEvent, spawn_watcher_service};
pub use websocket::{WsEventBroadcaster, WsMessage, ws_handler, spawn_event_forwarder};

